application: gjveron
version: 8
runtime: python27
threadsafe: yes
api_version: 1

handlers:
- url: /50x
  script: e50x.errorapplication
  
- url: /402
  script: e402.app
  
- url: /ip
  script: ip.app
  
- url: /blockjs
  static_dir: blockjs
  
- url: /spotfluxguard/
  static_files: spotfluxguard/spotfluxguard.js
  upload: spotfluxguard/spotfluxguard.js
  
- url: /spotfluxguard
  static_dir: spotfluxguard
  
- url: /
  static_files: home/index.html
  upload: home/index.html
  
- url: /
  static_dir: home

libraries:
- name: webapp2
  version: "2.5.2"